server:
  port: 7001

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiaolin158/demo2
          search-paths: src/main/resources
          username: VeryDifficultToName
          password: 123456